version: "3.2"

services:    
    keycloak:
        image: jboss/keycloak
        ports:
            - "8080:8080"
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
            - DB_VENDOR=mssql
            - DB_USER=wdp
            - DB_PASSWORD=WescoBLR0!
            - DB_ADDR=wdp-sql-server.database.windows.net
            - DB_DATABASE=wdp-iam
